tasks.test.alias = ["t"]
tasks.test.run = ["npm run all"]
tasks.lint = "npm run lint"
tasks."lint:fix" = "npm run format:write"

[tools]
node = '24'
git-cliff = 'latest'
gh = 'latest'
communique = 'latest'
